---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:
    - name: create vlad user
      tags: always
      user:
        name: vlad
        groups: root

    - name: add ssh key for vlad
      tags: always
      authorized_key:
        user: vlad
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/0KKBf5mJik2kS9yJaRO0/qS1E4PD/+twhiHKDAXWabdYEq/UhDWryY64Npx6+0+t+pc7jlZNkK4n77JZv6GC2DRjLOgWcaNGLO8GJZyTwmMQ8Q/oYadVmJYQjtCNxgDaS1/P9/v7srpJ9LWXjsCiS4z0GHVRsOv1w6JVdx9F3wX/uMVgs3dmMBtKfaR9CYe5s7X9JV7NbousmgYM6hMfIgOe019y1Euu537ArjYHhW4sgyoizB/r4nA2giNCzu3qQ+xB+tDJZD67R7q+jzVetwFcdKvsFvqs935Eeqfge+R4NT8vIURYhKt7PUyJhgq0YeuAKj35v7CbUgnXxwuSdHaJguZMd+VGoy8vvmRM9zN4wwNuensp4aHckgbE0I/G3duTDbodII5i5VEhBpVntFvr440I2lTpqFU3g9Yt+pRKjK+YUiQKiYJBDaQZvY7cRGGEmEDZTiPOo9t6n8i8p+Y23s7bHkz/xuruOuphy9I+Sg5LSk3vIFKbh4xPLTM= root@ansible-master"

    - name: add sudoers file for vlad
      tags: always
      copy:
        src: sudoer_vlad
        dest: /etc/sudoers.d/vlad
        owner: root
        group: root
        mode: 0440

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0755

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package
    tags: apache, apache2, ubuntu, debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 and php package
    tags: apache, apache2, centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: apache, httpd, CentOS
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somebody.net
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (debian)
      tags: dg, mariadb, debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: file, samba, debian, ubuntu, centos
      package:
        name: samba
        state: latest

